import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { EquipmentRecord } from '../types';

let cachedLogoDataUrl: string | null = null;

async function getLogoDataUrl(): Promise<string | null> {
  if (cachedLogoDataUrl) return cachedLogoDataUrl;

  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || 520;
        canvas.height = img.naturalHeight || 130;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, 0);
          // Standard PNG data URL generated by browser canvas
          cachedLogoDataUrl = canvas.toDataURL('image/png');
          resolve(cachedLogoDataUrl);
          return;
        }
      } catch (err) {
        console.warn('Erro ao converter logo no canvas:', err);
      }
      resolve(null);
    };
    img.onerror = () => resolve(null);
    img.src = '/logo_pbh_bhtrans.png';
  });
}

export async function exportSingleRecordPDF(record: EquipmentRecord) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const logoDataUrl = await getLogoDataUrl();

  // White Header Background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, 30, 'F');

  // Bottom border line for header
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.5);
  doc.line(10, 29, pageWidth - 10, 29);

  // Top Right Logo Timbre (PNG)
  if (logoDataUrl) {
    try {
      const logoWidth = 48;
      const logoHeight = 12;
      const logoX = pageWidth - 12 - logoWidth;
      doc.addImage(logoDataUrl, 'PNG', logoX, 8, logoWidth, logoHeight);
    } catch (e) {
      console.warn('Não foi possível renderizar a logo no PDF:', e);
    }
  }

  // Header Text Width Calculation to avoid logo collision
  const maxTextWidth = logoDataUrl ? pageWidth - 12 - 48 - 16 : pageWidth - 24;

  // GEAPI Title
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 12, 10, { maxWidth: maxTextWidth });

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85); // slate-700
  doc.text('Fiscalização Eletrônica — Ficha Detalhada do Equipamento', 12, 17, { maxWidth: maxTextWidth });

  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Código: ${record.CÓDIGO || 'N/A'} | Contrato: ${record.CONTRATO || 'N/A'} | Gerado em: ${new Date().toLocaleString('pt-BR')}`, 12, 24, { maxWidth: maxTextWidth });

  // Categorized Table Data - Filter out empty / null fields completely
  const rawCategories = [
    {
      title: 'Identificação & Contrato',
      fields: [
        ['CONTRATO', record.CONTRATO],
        ['CONTRATADA', record.CONTRATADA],
        ['CÓDIGO', record.CÓDIGO],
        ['Nº DE SÉRIE', record['Nº DE SÉRIE']],
        ['COD LOG', record['COD LOG']],
      ]
    },
    {
      title: 'Localização & Infraestrutura',
      fields: [
        ['ENDEREÇO COMPLETO', record['ENDEREÇO COMPLETO']],
        ['CORREDOR', record.CORREDOR],
        ['SENTIDO', record.SENTIDO],
        ['BAIRRO', record.BAIRRO],
        ['REGIONAL', record.REGIONAL],
        ['COORD_LAT_LONG', record.COORD_LAT_LONG],
      ]
    },
    {
      title: 'Especificações Operacionais',
      fields: [
        ['TIPO', record.TIPO],
        ['FAIXAS', record.FAIXAS ? String(record.FAIXAS) : ''],
        ['Velocidade Fiscalizada', record['Velocidade Fiscalizada']],
        ['Situação', record.Situação],
        ['CONDIÇÃO', record.CONDIÇÃO],
        ['DIF Pareado', record['DIF Pareado']],
        ['OS', record.OS],
        ['ANO', record.ANO],
      ]
    },
    {
      title: 'Datas, Aferição & Observações',
      fields: [
        ['Data de Início de Operação', record['Data início operação']],
        ['Data de Aceite', record['Data de aceite']],
        ['Data da Aferição', record['Data da Aferição']],
        ['Data de Vencimento da Aferição', record['Data de Vencimento da Aferição']],
        ['Observações', record.Observações],
      ]
    }
  ];

  let startY = 34;

  rawCategories.forEach((cat) => {
    // Only keep non-empty fields
    const validFields = cat.fields.filter(([_, val]) => {
      if (val === undefined || val === null) return false;
      const str = String(val).trim();
      return str !== '' && str !== '-' && str !== '(Vazio)';
    });

    // Skip section if no valid data
    if (validFields.length === 0) return;

    doc.setFillColor(241, 245, 249); // slate-100
    doc.rect(12, startY, pageWidth - 24, 6.5, 'F');
    doc.setTextColor(30, 41, 59); // slate-800
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.text(cat.title.toUpperCase(), 14, startY + 4.5);

    startY += 7.5;

    autoTable(doc, {
      startY: startY,
      margin: { left: 12, right: 12 },
      head: [['Campo', 'Valor']],
      body: validFields.map(([label, val]) => [label, String(val).trim()]),
      theme: 'grid',
      headStyles: {
        fillColor: [30, 41, 59], // slate-800
        textColor: 255,
        fontSize: 8,
        fontStyle: 'bold',
        cellPadding: 2
      },
      bodyStyles: {
        fontSize: 8,
        textColor: 51,
        cellPadding: 2
      },
      columnStyles: {
        0: { cellWidth: 55, fontStyle: 'bold', fillColor: [248, 250, 252] },
        1: { cellWidth: 'auto' }
      }
    });

    startY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  });

  // Footer Legend
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageHeight - 16, pageWidth, 16, 'F');
  
  doc.setFontSize(6.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFont('helvetica', 'normal');
  const legendText = 'Legenda: 2740/2024 - ELISEU KOPP & CIA LTDA.; 2741/2024 - SPLICE INDÚSTRIA, COMÉRCIO E SERVIÇOS LTDA.; 2742/2024 - CONSÓRCIO TRÂNSITO SEGURO; DIF: detector de invasão de faixa exclusiva de ônibus | DAS: detector de avanço de semáforo vermelho | DTLP: detector de tráfego em local/horário proibido | DCP: detector de conversão em local proibido | CEV: controlador eletrônico de velocidade.';
  doc.text(legendText, 12, pageHeight - 7, { maxWidth: pageWidth - 24 });

  doc.save(`GEAPI-Equipamento-${record.CÓDIGO || record.id}.pdf`);
}

export async function exportFilteredRecordsPDF(records: EquipmentRecord[], filterSummary?: string) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const logoDataUrl = await getLogoDataUrl();

  // White Header Banner
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(10, 27, pageWidth - 10, 27);

  // Top Right Logo Timbre (PNG)
  if (logoDataUrl) {
    try {
      const logoWidth = 50;
      const logoHeight = 12.5;
      const logoX = pageWidth - 10 - logoWidth;
      doc.addImage(logoDataUrl, 'PNG', logoX, 7, logoWidth, logoHeight);
    } catch (e) {
      console.warn('Não foi possível renderizar a logo no PDF:', e);
    }
  }

  // Text width limit to avoid logo overlay
  const maxTextWidth = logoDataUrl ? pageWidth - 10 - 50 - 15 : pageWidth - 20;

  // GEAPI Title
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 10, 9, { maxWidth: maxTextWidth });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text('Fiscalização Eletrônica — Relatório Compilado de Equipamentos', 10, 15, { maxWidth: maxTextWidth });

  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`Total de registros: ${records.length} | Exportado em: ${new Date().toLocaleString('pt-BR')} ${filterSummary ? '| Filtros: ' + filterSummary : ''}`, 10, 22, { maxWidth: maxTextWidth });

  // Table columns
  const tableHead = [
    'CÓDIGO',
    'CONTRATO',
    'TIPO',
    'FAIXAS',
    'SITUAÇÃO',

