import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { EquipmentRecord } from '../types';
import { captureMap } from './mapExport';

let cachedLogoDataUrl: string | null = null;

async function getLogoDataUrl(): Promise<string | null> {
  if (cachedLogoDataUrl) return cachedLogoDataUrl;

  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || 520;
        canvas.height = img.naturalHeight || 130;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, 0);
          // Standard PNG data URL generated by browser canvas
          cachedLogoDataUrl = canvas.toDataURL('image/png');
          resolve(cachedLogoDataUrl);
          return;
        }
      } catch (err) {
        console.warn('Erro ao converter logo no canvas:', err);
      }
      resolve(null);
    };
    img.onerror = () => resolve(null);
    img.src = '/logo_pbh_bhtrans.png';
  });
}

const formatDate = (dateStr?: string) => {
  if (!dateStr) return '-';
  try {
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) return dateStr;
    return new Intl.DateTimeFormat('pt-BR').format(date);
  } catch {
    return dateStr;
  }
};

const addCustomFooter = (doc: any, pageWidth: number, pageHeight: number, pageNumText?: string) => {
  const footerHeight = 16;
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageHeight - footerHeight, pageWidth, footerHeight, 'F');
  
  doc.setFontSize(6.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFont('helvetica', 'normal');
  
  doc.text('GEAPI — Gerência de Análise e Processamento de Infrações | Prefeitura de Belo Horizonte', 12, pageHeight - 10);
  doc.text('Desenvolvido por Caio Henriques de O. L. Cordeiro - caiohenriques@pbh.gov.br', 12, pageHeight - 6);
  doc.text('https://geapife.vercel.app/', 12, pageHeight - 2);

  if (pageNumText) {
    doc.text(pageNumText, pageWidth - 12, pageHeight - 6, { align: 'right' });
  }
};

export async function exportSingleRecordPDF(record: EquipmentRecord) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const logoDataUrl = await getLogoDataUrl();

  // White Header Background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, 30, 'F');

  // Bottom border line for header
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.5);
  doc.line(10, 29, pageWidth - 10, 29);

  // Top Right Logo Timbre (PNG)
  if (logoDataUrl) {
    try {
      const logoWidth = 48;
      const logoHeight = 12;
      const logoX = pageWidth - 12 - logoWidth;
      doc.addImage(logoDataUrl, 'PNG', logoX, 8, logoWidth, logoHeight);
    } catch (e) {
      console.warn('Não foi possível renderizar a logo no PDF:', e);
    }
  }

  // Header Text Width Calculation to avoid logo collision
  const maxTextWidth = logoDataUrl ? pageWidth - 12 - 48 - 16 : pageWidth - 24;

  // GEAPI Title
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 12, 10, { maxWidth: maxTextWidth });

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85); // slate-700
  doc.text('Fiscalização Eletrônica — Ficha Detalhada do Equipamento', 12, 17, { maxWidth: maxTextWidth });

  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Código: ${record.CÓDIGO || 'N/A'} | Contrato: ${record.CONTRATO || 'N/A'} | Gerado em: ${new Date().toLocaleString('pt-BR')}`, 12, 24, { maxWidth: maxTextWidth });

  // Categorized Table Data - Filter out empty / null fields completely
  const rawCategories = [
    {
      title: 'Identificação & Contrato',
      fields: [
        ['CONTRATO', record.CONTRATO],
        ['CONTRATADA', record.CONTRATADA],
        ['CÓDIGO', record.CÓDIGO],
        ['Nº DE SÉRIE', record['Nº DE SÉRIE']],
        ['COD LOG', record['COD LOG']],
      ]
    },
    {
      title: 'Localização & Infraestrutura',
      fields: [
        ['ENDEREÇO COMPLETO', record['ENDEREÇO COMPLETO']],
        ['CORREDOR', record.CORREDOR],
        ['SENTIDO', record.SENTIDO],
        ['BAIRRO', record.BAIRRO],
        ['REGIONAL', record.REGIONAL],
        ['COORD_LAT_LONG', record.COORD_LAT_LONG],
      ]
    },
    {
      title: 'Especificações Operacionais',
      fields: [
        ['TIPO', record.TIPO],
        ['FAIXAS', record.FAIXAS ? String(record.FAIXAS) : ''],
        ['Velocidade Fiscalizada', record['Velocidade Fiscalizada']],
        ['Situação', record.Situação],
        ['CONDIÇÃO', record.CONDIÇÃO],
        ['DIF Pareado', record['DIF Pareado']],
        ['OS', record.OS],
        ['ANO', record.ANO],
      ]
    },
    {
      title: 'Datas, Aferição & Observações',
      fields: [
        ['Data de Início de Operação', record['Data início operação']],
        ['Data de Aceite', record['Data de aceite']],
        ['Data da Aferição', record['Data da Aferição']],
        ['Data de Vencimento da Aferição', record['Data de Vencimento da Aferição']],
        ['Observações', record.Observações],
      ]
    }
  ];

  let startY = 34;

  rawCategories.forEach((cat) => {
    // Only keep non-empty fields
    const validFields = cat.fields.filter(([_, val]) => {
      if (val === undefined || val === null) return false;
      const str = String(val).trim();
      return str !== '' && str !== '-' && str !== '(Vazio)';
    });

    // Skip section if no valid data
    if (validFields.length === 0) return;

    doc.setFillColor(241, 245, 249); // slate-100
    doc.rect(12, startY, pageWidth - 24, 6.5, 'F');
    doc.setTextColor(30, 41, 59); // slate-800
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.text(cat.title.toUpperCase(), 14, startY + 4.5);

    startY += 7.5;

    autoTable(doc, {
      startY: startY,
      margin: { left: 12, right: 12 },
      head: [['Campo', 'Valor']],
      body: validFields.map(([label, val]) => [label, String(val).trim()]),
      theme: 'grid',
      headStyles: {
        fillColor: [30, 41, 59], // slate-800
        textColor: 255,
        fontSize: 8,
        fontStyle: 'bold',
        cellPadding: 2
      },
      bodyStyles: {
        fontSize: 8,
        textColor: 51,
        cellPadding: 2
      },
      columnStyles: {
        0: { cellWidth: 55, fontStyle: 'bold', fillColor: [248, 250, 252] },
        1: { cellWidth: 'auto' }
      }
    });

    startY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  });

  // Footer Legend
  const pageHeight = doc.internal.pageSize.getHeight();
  addCustomFooter(doc, pageWidth, pageHeight, 'Página 1 de 1');

  doc.save(`GEAPI-Equipamento-${record.CÓDIGO || record.id}.pdf`);
}

export async function exportFilteredRecordsPDF(records: EquipmentRecord[], filterSummary?: string) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const logoDataUrl = await getLogoDataUrl();

  // White Header Banner
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(10, 27, pageWidth - 10, 27);

  // Top Right Logo Timbre (PNG)
  if (logoDataUrl) {
    try {
      const logoWidth = 50;
      const logoHeight = 12.5;
      const logoX = pageWidth - 10 - logoWidth;
      doc.addImage(logoDataUrl, 'PNG', logoX, 7, logoWidth, logoHeight);
    } catch (e) {
      console.warn('Não foi possível renderizar a logo no PDF:', e);
    }
  }

  // Text width limit to avoid logo overlay
  const maxTextWidth = logoDataUrl ? pageWidth - 10 - 50 - 15 : pageWidth - 20;

  // GEAPI Title
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 10, 9, { maxWidth: maxTextWidth });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text('Fiscalização Eletrônica — Relatório Compilado de Equipamentos', 10, 15, { maxWidth: maxTextWidth });

  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`Total de registros: ${records.length} | Exportado em: ${new Date().toLocaleString('pt-BR')} ${filterSummary ? '| Filtros: ' + filterSummary : ''}`, 10, 22, { maxWidth: maxTextWidth });

  // Table columns
  const tableHead = [
    'CÓDIGO',
    'CONTRATO',
    'TIPO',
    'FAIXAS',
    'SITUAÇÃO',
    'ENDEREÇO COMPLETO',
    'BAIRRO',
    'INÍCIO DE OPERAÇÃO',
    'DATA DE ACEITE',
    'CONDIÇÃO'
  ];

  const tableBody = records.map((r) => [
    r.CÓDIGO?.trim() || '-',
    r.CONTRATO?.trim() || '-',
    r.TIPO?.trim() || '-',
    r.FAIXAS ? String(r.FAIXAS) : '-',
    r.Situação?.trim() || '-',
    r['ENDEREÇO COMPLETO']?.trim() || '-',
    r.BAIRRO?.trim() || '-',
    r['Data início operação']?.trim() || '-',
    r['Data de aceite']?.trim() || '-',
    r.CONDIÇÃO?.trim() || '-'
  ]);

  autoTable(doc, {
    startY: 30,
    margin: { left: 10, right: 10, top: 30, bottom: 18 },
    head: [tableHead],
    body: tableBody,
    theme: 'striped',
    headStyles: {
      fillColor: [30, 41, 59], // slate-800 header to complement white background
      textColor: 255,
      fontSize: 7.5,
      fontStyle: 'bold',
      cellPadding: 2
    },
    bodyStyles: {
      fontSize: 7,
      textColor: 51,
      cellPadding: 1.5
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    didDrawPage: (data) => {
      // Draw top header banner & logo timbre on page 2 and beyond
      if (data.pageNumber > 1) {
        doc.setFillColor(255, 255, 255);
        doc.rect(0, 0, pageWidth, 28, 'F');

        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.5);
        doc.line(10, 27, pageWidth - 10, 27);

        if (logoDataUrl) {
          try {
            const logoWidth = 50;
            const logoHeight = 12.5;
            const logoX = pageWidth - 10 - logoWidth;
            doc.addImage(logoDataUrl, 'PNG', logoX, 7, logoWidth, logoHeight);
          } catch (e) {
            console.warn('Não foi possível renderizar a logo no PDF:', e);
          }
        }

        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 10, 9, { maxWidth: maxTextWidth });

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(51, 65, 85);
        doc.text('Fiscalização Eletrônica — Relatório Compilado de Equipamentos', 10, 15, { maxWidth: maxTextWidth });

        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text(`Página ${data.pageNumber} | Total de registros: ${records.length}`, 10, 22, { maxWidth: maxTextWidth });
      }

      addCustomFooter(doc, pageWidth, pageHeight, `Página ${data.pageNumber}`);
    }
  });

  doc.save(`GEAPI-Relatorio-Equipamentos-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export async function exportCustomReportPDF(records: EquipmentRecord[], filtersApplied: any) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  
  let logoDataUrl = null;
  try {
    logoDataUrl = await getLogoDataUrl();
  } catch (e) {
    console.warn('Could not load logo for PDF', e);
  }

  // ----------- PAGE 1: RESUMO EXECUTIVO -----------
  // Bottom border line for header
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.5);
  doc.line(10, 29, pageWidth - 10, 29);

  // Top Right Logo Timbre (PNG)
  if (logoDataUrl) {
    try {
      const logoWidth = 48;
      const logoHeight = 12;
      const logoX = pageWidth - 12 - logoWidth;
      doc.addImage(logoDataUrl, 'PNG', logoX, 8, logoWidth, logoHeight);
    } catch (e) {}
  }

  const maxTextWidth = logoDataUrl ? pageWidth - 12 - 48 - 16 : pageWidth - 24;
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 12, 10, { maxWidth: maxTextWidth });
  
  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('RESUMO EXECUTIVO - INDICADORES', 12, 17, { maxWidth: maxTextWidth });
  
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Gerado em: ${new Date().toLocaleString('pt-BR')} | Total de Equipamentos: ${records.length}`, 12, 24, { maxWidth: maxTextWidth });

  // Filters Summary
  let cursorY = 36;
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('DISCLAIMER: Este relatório apresenta os dados consolidados das seleções feitas no filtro conforme a seguir.', 12, cursorY);
  cursorY += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Filtros Aplicados', 12, cursorY);
  cursorY += 6;

  doc.setFontSize(9);
  const activeFilters: { label: string; value: string }[] = [];
  if (filtersApplied.codigo) activeFilters.push({ label: 'Códigos', value: filtersApplied.codigo });
  if (filtersApplied.corredores && filtersApplied.corredores.length > 0) activeFilters.push({ label: 'Corredores', value: filtersApplied.corredores.join(', ') });
  if (filtersApplied.contratos && filtersApplied.contratos.length > 0) activeFilters.push({ label: 'Contratos', value: filtersApplied.contratos.join(', ') });
  if (filtersApplied.situacoes && filtersApplied.situacoes.length > 0) activeFilters.push({ label: 'Status do equip.', value: filtersApplied.situacoes.join(', ') });
  if (filtersApplied.condicoes && filtersApplied.condicoes.length > 0) activeFilters.push({ label: 'Situações', value: filtersApplied.condicoes.join(', ') });
  if (filtersApplied.regionais && filtersApplied.regionais.length > 0) activeFilters.push({ label: 'Regionais', value: filtersApplied.regionais.join(', ') });
  if (filtersApplied.bairros && filtersApplied.bairros.length > 0) activeFilters.push({ label: 'Bairros', value: filtersApplied.bairros.join(', ') });
  if (filtersApplied.tipos && filtersApplied.tipos.length > 0) activeFilters.push({ label: 'Tipo de equip.', value: filtersApplied.tipos.join(', ') });
  if (filtersApplied.os && filtersApplied.os.length > 0) activeFilters.push({ label: 'Nº O.S.', value: filtersApplied.os.join(', ') });
  
  if (filtersApplied.inicioOp && (filtersApplied.inicioOp.de || filtersApplied.inicioOp.ate)) {
    activeFilters.push({ label: 'Início de Oper.', value: `${filtersApplied.inicioOp.de || '---'} até ${filtersApplied.inicioOp.ate || '---'}` });
  }
  if (filtersApplied.aceite && (filtersApplied.aceite.de || filtersApplied.aceite.ate)) {
    activeFilters.push({ label: 'Data de Aceite', value: `${filtersApplied.aceite.de || '---'} até ${filtersApplied.aceite.ate || '---'}` });
  }

  if (activeFilters.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('Relatório Global (Nenhum filtro aplicado)', 12, cursorY);
    cursorY += 6;
  } else {
    let fCol = 0;
    activeFilters.forEach((f) => {
      let x = 12 + (fCol * 95);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(f.label + ':', x, cursorY);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      let val = doc.splitTextToSize(f.value, 95 - doc.getTextWidth(f.label + ': ') - 2);
      doc.text(val[0] || '', x + doc.getTextWidth(f.label + ': ') + 1, cursorY);
      
      fCol++;
      if (fCol > 1) {
        fCol = 0;
        cursorY += 5;
      }
    });
    if (fCol !== 0) cursorY += 5;
  }
  cursorY += 2;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(10, cursorY, pageWidth - 10, cursorY);
  cursorY += 6;

  // Calculando Indicadores (Igual à aba Indicadores)
  let totalFaixas = 0;
  const locaisUnicos = new Set<string>();
  
  let equipmentsOperacao = 0;
  let equipmentsImplantacao = 0;
  let equipmentsRelocacao = 0;

  const contratoStats = new Map<string, { count: number; faixas: number; locais: Set<string> }>();
  const tipoStats = new Map<string, { count: number; faixas: number; locais: Set<string> }>();

  records.forEach(r => {
    const fx = (r.FAIXAS || 0);
    totalFaixas += fx;
    
    const end = (r['ENDEREÇO COMPLETO'] || '').trim().toLowerCase();
    if (end) locaisUnicos.add(end);
    
    const sit = (r.Situação || '').toUpperCase();
    if (sit.includes('OPERAÇÃO') || sit.includes('OPERACAO')) equipmentsOperacao += 1;
    else if (sit.includes('RELOCAÇÃO') || sit.includes('RELOCACAO')) equipmentsRelocacao += 1;
    else equipmentsImplantacao += 1;
    
    const cont = r.CONTRATO || 'Sem Contrato';
    if (!contratoStats.has(cont)) contratoStats.set(cont, { count: 0, faixas: 0, locais: new Set() });
    const cStat = contratoStats.get(cont)!;
    cStat.count += 1;
    cStat.faixas += fx;
    if (end) cStat.locais.add(end);

    const tip = r.TIPO || 'Sem Tipo';
    if (!tipoStats.has(tip)) tipoStats.set(tip, { count: 0, faixas: 0, locais: new Set() });
    const tStat = tipoStats.get(tip)!;
    tStat.count += 1;
    tStat.faixas += fx;
    if (end) tStat.locais.add(end);
  });

  // KPI boxes (4 boxes like Indicadores)
  const boxWidth = 43;
  
  // 1. Total Equipamentos
  doc.setDrawColor(191, 219, 254);
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(12, cursorY, boxWidth, 16, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(37, 99, 235);
  doc.text(String(records.length), 16, cursorY + 8);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Total Equipamentos', 16, cursorY + 13);

  // 2. Total Faixas
  doc.setDrawColor(167, 243, 208);
  doc.setFillColor(236, 253, 245);
  doc.roundedRect(12 + boxWidth + 4, cursorY, boxWidth, 16, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(5, 150, 105);
  doc.text(String(totalFaixas), 16 + boxWidth + 4, cursorY + 8);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Faixas Fiscalizadas', 16 + boxWidth + 4, cursorY + 13);

  // 3. Locais Unicos
  doc.setDrawColor(253, 230, 138);
  doc.setFillColor(255, 251, 235);
  doc.roundedRect(12 + (boxWidth * 2) + 8, cursorY, boxWidth, 16, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(217, 119, 6);
  doc.text(String(locaisUnicos.size), 16 + (boxWidth * 2) + 8, cursorY + 8);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Locais Únicos', 16 + (boxWidth * 2) + 8, cursorY + 13);

  // 4. Indicadores Situacao
  doc.setDrawColor(233, 213, 255);
  doc.setFillColor(250, 245, 255);
  doc.roundedRect(12 + (boxWidth * 3) + 12, cursorY, boxWidth, 16, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text('Indicadores', 16 + (boxWidth * 3) + 12, cursorY + 6);
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Operação: ${equipmentsOperacao}`, 16 + (boxWidth * 3) + 12, cursorY + 10);
  doc.text(`Reloc.: ${equipmentsRelocacao} | Impl.: ${equipmentsImplantacao}`, 16 + (boxWidth * 3) + 12, cursorY + 14);

  cursorY += 24;

  // Gráficos de Indicadores
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Painel de Indicadores (Gráficos)', 12, cursorY);
  cursorY += 6;

  // Function to render a horizontal bar chart
  const renderHorizontalChart = (title: string, data: {label: string, val: number}[], xPos: number, yPos: number, cWidth: number, color: [number, number, number]) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(title, xPos, yPos);
    
    if (data.length === 0) return;
    const maxVal = Math.max(...data.map(d => d.val), 1);
    
    let cY = yPos + 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    
    data.forEach((item) => {
      doc.setTextColor(71, 85, 105);
      const label = item.label.substring(0, 18);
      doc.text(label, xPos, cY + 3);
      
      const barX = xPos + 22;
      const maxBarW = cWidth - 32;
      const barW = (item.val / maxVal) * maxBarW;
      
      doc.setFillColor(...color);
      doc.rect(barX, cY - 0.5, barW, 3.5, 'F');
      
      doc.setTextColor(15, 23, 42);
      doc.text(String(item.val), barX + barW + 1.5, cY + 3);
      cY += 6;
    });
  };

  // Prepare Data - Ordenado Alfabeticamente para Contrato!
  const contArray = Array.from(contratoStats.entries()).sort((a,b) => a[0].localeCompare(b[0]));
  const tipoArray = Array.from(tipoStats.entries()).sort((a,b) => b[1].faixas - a[1].faixas).slice(0, 5); // top 5 tipos para faixas
  const tipoLocaisArray = Array.from(tipoStats.entries()).sort((a,b) => b[1].locais.size - a[1].locais.size).slice(0, 5);

  const colW = (pageWidth - 24) / 3;
  
  // Row 1: Faixas, Equipamentos, Locais por Contrato
  renderHorizontalChart('Faixas por Contrato', contArray.map(c => ({label: c[0], val: c[1].faixas})), 12, cursorY, colW, [59, 130, 246]);
  renderHorizontalChart('Equip. por Contrato', contArray.map(c => ({label: c[0], val: c[1].count})), 12 + colW, cursorY, colW, [139, 92, 246]);
  renderHorizontalChart('Locais por Contrato', contArray.map(c => ({label: c[0], val: c[1].locais.size})), 12 + (colW * 2), cursorY, colW, [249, 115, 22]);

  cursorY += (contArray.length * 6) + 12;

  // Row 2: Tipos (Faixas e Locais)
  renderHorizontalChart('Faixas por Tipo', tipoArray.map(c => ({label: c[0], val: c[1].faixas})), 12, cursorY, colW * 1.5, [16, 185, 129]);
  renderHorizontalChart('Locais por Tipo', tipoLocaisArray.map(c => ({label: c[0], val: c[1].locais.size})), 12 + (colW * 1.5), cursorY, colW * 1.5, [139, 92, 246]);

  // ----------- PAGE 2: MAPA -----------
  const mapElement = document.querySelector('.leaflet-container') as HTMLElement;
  if (mapElement) {
    try {
      const canvas = await html2canvas(mapElement, { useCORS: true, logging: false });
      const mapDataUrl = canvas.toDataURL('image/jpeg', 0.8);
      
      doc.addPage();
      
      // Bottom border line for header
      doc.setDrawColor(226, 232, 240); // slate-200
      doc.setLineWidth(0.5);
      doc.line(10, 29, pageWidth - 10, 29);

      if (logoDataUrl) {
        try {
          const logoWidth = 48;
          const logoHeight = 12;
          const logoX = pageWidth - 12 - logoWidth;
          doc.addImage(logoDataUrl, 'PNG', logoX, 8, logoWidth, logoHeight);
        } catch (e) {}
      }

      doc.setTextColor(15, 23, 42); // slate-900
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 12, 10, { maxWidth: maxTextWidth });
      
      doc.setFontSize(9.5);
      doc.text('MAPA DE LOCALIZAÇÃO DOS EQUIPAMENTOS', 12, 17, { maxWidth: maxTextWidth });

      // Draw the map image
      doc.addImage(mapDataUrl, 'JPEG', 12, 35, 186, 139.5);
      
      // Draw a black border around the map
      doc.setDrawColor(15, 23, 42); // Very dark slate (near black)
      doc.setLineWidth(0.5);
      doc.rect(12, 35, 186, 139.5);

      addCustomFooter(doc, pageWidth, doc.internal.pageSize.getHeight(), `Página ${doc.internal.getNumberOfPages()}`);
    } catch (e) {
      console.error('Erro ao gerar mapa pro PDF', e);
    }
  }
  // ----------- PAGE 3+... DADOS DOS EQUIPAMENTOS -----------
  
  // We'll iterate through the records and print the fichas
  records.forEach((record, idx) => {
    doc.addPage();
    
    // Bottom border line for header
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setLineWidth(0.5);
    doc.line(10, 29, pageWidth - 10, 29);

    // Top Right Logo Timbre (PNG)
    if (logoDataUrl) {
      try {
        const logoWidth = 48;
        const logoHeight = 12;
        const logoX = pageWidth - 12 - logoWidth;
        doc.addImage(logoDataUrl, 'PNG', logoX, 8, logoWidth, logoHeight);
      } catch (e) {}
    }

    // Header Text Width Calculation to avoid logo collision
    const maxTextWidth = logoDataUrl ? pageWidth - 12 - 48 - 16 : pageWidth - 24;

    // GEAPI Title
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('GERÊNCIA DE ANÁLISE E PROCESSAMENTO DE INFRAÇÕES - GEAPI', 12, 10, { maxWidth: maxTextWidth });
    
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85); // slate-700
    doc.text('Ficha Detalhada do Equipamento (Relatório)', 12, 17, { maxWidth: maxTextWidth });
    
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Código: ${record.CÓDIGO || 'N/A'} | Contrato: ${record.CONTRATO || 'N/A'} | Gerado em: ${new Date().toLocaleString('pt-BR')}`, 12, 24, { maxWidth: maxTextWidth });

    // Categorized Table Data - Filter out empty / null fields completely
    const rawCategories = [
      {
        title: 'Identificação & Contrato',
        fields: [
          ['CONTRATO', record.CONTRATO],
          ['CONTRATADA', record.CONTRATADA],
          ['CÓDIGO', record.CÓDIGO],
          ['Nº DE SÉRIE', record['Nº DE SÉRIE']],
          ['COD LOG', record['COD LOG']],
        ]
      },
      {
        title: 'Localização & Infraestrutura',
        fields: [
          ['ENDEREÇO COMPLETO', record['ENDEREÇO COMPLETO']],
          ['CORREDOR', record.CORREDOR],
          ['SENTIDO', record.SENTIDO],
          ['BAIRRO', record.BAIRRO],
          ['REGIONAL', record.REGIONAL],
          ['COORD_LAT_LONG', record.COORD_LAT_LONG],
        ]
      },
      {
        title: 'Especificações Operacionais',
        fields: [
          ['TIPO', record.TIPO],
          ['FAIXAS', record.FAIXAS ? String(record.FAIXAS) : ''],
          ['Velocidade Fiscalizada', record['Velocidade Fiscalizada'] || record.rawFields['VELOCIDADE']],
          ['Situação', record.Situação],
          ['CONDIÇÃO', record.CONDIÇÃO],
          ['DIF Pareado', record['DIF Pareado']],
          ['OS', record.OS],
          ['ANO', record.ANO],
        ]
      },
      {
        title: 'Datas, Aferição & Observações',
        fields: [
          ['Data de Início de Operação', formatDate(record['Data início operação'] || record.rawFields['INÍCIO OPERAÇÃO'])],
          ['Data de Aceite', formatDate(record['Data de aceite'] || record.rawFields['DATA DO ACEITE'])],
          ['Data da Aferição', formatDate(record['Data da Aferição'] || record.rawFields['DATA DA AFERIÇÃO'])],
          ['Data de Vencimento da Aferição', formatDate(record['Data de Vencimento da Aferição'] || record.rawFields['DATA DO VENCIMENTO DA AFERIÇÃO'])],
          ['Observações', record.Observações || record.rawFields['OBSERVAÇÃO']],
        ]
      }
    ];

    let startY = 34;

    rawCategories.forEach((cat) => {
      // Only keep non-empty fields
      const validFields = cat.fields.filter(([_, val]) => {
        if (val === undefined || val === null) return false;
        const str = String(val).trim();
        return str !== '' && str !== '-' && str !== '(Vazio)';
      });
      
      // Skip section if no valid data
      if (validFields.length === 0) return;

      doc.setFillColor(241, 245, 249); // slate-100
      doc.rect(12, startY, pageWidth - 24, 6.5, 'F');
      
      doc.setTextColor(30, 41, 59); // slate-800
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.text(cat.title, 14, startY + 4.5);
      
      autoTable(doc, {
        startY: startY + 8,
        body: validFields,
        theme: 'plain',
        styles: {
          fontSize: 8.5,
          cellPadding: { top: 1.5, bottom: 1.5, left: 2, right: 2 },
          font: 'helvetica'
        },
        columnStyles: {
          0: { cellWidth: 70, fontStyle: 'bold', textColor: [71, 85, 105] }, // Property name
          1: { cellWidth: 'auto', textColor: [15, 23, 42] } // Value
        },
        margin: { left: 12, right: 12 },
      });

      startY = (doc as any).lastAutoTable.finalY + 6;
    });

    // Add Footer with page numbers
    const pageCount = (doc.internal as any).getNumberOfPages();
    const str = `Equipamento ${idx + 1} de ${records.length} | Página ${pageCount}`;
    addCustomFooter(doc, pageWidth, doc.internal.pageSize.getHeight(), str);
  });

  doc.save(`Relatorio_Demanda_${Date.now()}.pdf`);
}
